version: "3.9"

services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=NumberHoas

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5086:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=NumberHoas;Username=postgres;Password=postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - INTERNAL_API_URL=http://backend:8080
      - NEXT_PUBLIC_API_URL=http://localhost:5086
    depends_on:
      - backend
  
volumes:
  pgdata: