// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NumberHoas.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20250805105055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("NumberHoas.Models.Game", b =>
                {
                    b.Property<Guid>("gameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("authorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("gameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("timeLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("gameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NumberHoas.Models.Question", b =>
                {
                    b.Property<Guid>("questionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("correctAnswers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("playerAnswer")
                        .HasColumnType("TEXT");

                    b.Property<int>("questionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("sessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("questionId");

                    b.HasIndex("sessionId");

                    b.ToTable("SessionQuestions");
                });

            modelBuilder.Entity("NumberHoas.Models.Rule", b =>
                {
                    b.Property<Guid>("ruleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("divisibleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("gameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("replacedWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ruleId");

                    b.HasIndex("gameId");

                    b.ToTable("GameRules");
                });

            modelBuilder.Entity("NumberHoas.Models.Session", b =>
                {
                    b.Property<Guid>("sessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("gameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("playerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("score")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("TEXT");

                    b.HasKey("sessionId");

                    b.HasIndex("gameId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("NumberHoas.Models.Question", b =>
                {
                    b.HasOne("NumberHoas.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("sessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NumberHoas.Models.Rule", b =>
                {
                    b.HasOne("NumberHoas.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("gameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NumberHoas.Models.Session", b =>
                {
                    b.HasOne("NumberHoas.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("gameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
