// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NumberHoas.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NumberHoas.Models.Game", b =>
                {
                    b.Property<Guid>("gameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("authorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("gameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("range")
                        .HasColumnType("integer");

                    b.Property<int>("timeLimit")
                        .HasColumnType("integer");

                    b.HasKey("gameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NumberHoas.Models.Question", b =>
                {
                    b.Property<Guid>("questionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("correctAnswers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("playerAnswer")
                        .HasColumnType("text");

                    b.Property<int>("questionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("sessionId")
                        .HasColumnType("uuid");

                    b.HasKey("questionId");

                    b.HasIndex("sessionId");

                    b.ToTable("SessionQuestions");
                });

            modelBuilder.Entity("NumberHoas.Models.Rule", b =>
                {
                    b.Property<Guid>("ruleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("divisibleNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("gameId")
                        .HasColumnType("uuid");

                    b.Property<string>("replacedWord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ruleId");

                    b.HasIndex("gameId");

                    b.ToTable("GameRules");
                });

            modelBuilder.Entity("NumberHoas.Models.Session", b =>
                {
                    b.Property<Guid>("sessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("gameId")
                        .HasColumnType("uuid");

                    b.Property<string>("playerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("sessionId");

                    b.HasIndex("gameId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("NumberHoas.Models.Question", b =>
                {
                    b.HasOne("NumberHoas.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("sessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NumberHoas.Models.Rule", b =>
                {
                    b.HasOne("NumberHoas.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("gameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NumberHoas.Models.Session", b =>
                {
                    b.HasOne("NumberHoas.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("gameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
